name: 'Architus Upload API Client'
description: 'Uploads build archives to the Architus staging upload API'
inputs:
  archive-path:
    description: 'Path of the build archive'
    required: true
  event:
    description: 'Cause of CI run (`pull_request` or `push`)'
    required: true
  token:
    description: 'Upload API token'
    required: true
  api-root:
    description: 'Root URL of upload API (without trailing slash)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
